languageCode = 'en-us'
title = 'Pratik Deoghare'
theme = 'anubis'

[author]
name = "Pratik Deoghare"

[params]
author = "Pratik Deoghare"
dateFormat = "2006-01-02"
paginationSinglePost = true
style = "light-without-switcher"
readMore = true
readNextPosts = 2
copyCodeButton = false
rssAsSocialIcon = false
mathjax = true

[menu]

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 1

[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 2

[[menu.main]]
name = "Archive"
identifier = "archive"
url = "/posts/"
weight = 3